name: Post merge

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
